0

In [ ]:
A) Find out how many data engineer programs have been applied and which schools have applied them along

myh_db=# SELECT
    Utbildningsnamn,
    "utbildningsanordnare administrativ enhet"
FROM myh_2024
WHERE  Utbildningsnamn ILIKE 'Data engineer';

 utbildningsnamn | utbildningsanordnare administrativ enhet 
-----------------+------------------------------------------
 Data Engineer   | Nackademin AB
 Data engineer   | JENSEN Education School AB
 Data engineer   | JENSEN Education School AB
 Data engineer   | JENSEN Education School AB
 Data Engineer   | Skill Utbildning AB
 Data Engineer   | Nackademin AB
 Data Engineer   | IT-Högskolan Stockholm AB
(7 rows)

B) Find out number of data engineer programs that got approved.

SELECT
    Utbildningsnamn,
    Beslut,
    "utbildningsanordnare administrativ enhet"
FROM myh_2024
WHERE Utbildningsnamn ILIKE 'Data engineer' AND Beslut = 'Beviljad';


 utbildningsnamn |  beslut  | utbildningsanordnare administrativ enhet 
-----------------+----------+------------------------------------------
 Data Engineer   | Beviljad | Nackademin AB
(1 row)

C) Count number of approved programs in each of the education categories (utbildningsområde)

SELECT
    COUNT(utbildningsnamn) AS Utbildning,
    utbildningsområde
FROM myh_2024
GROUP BY utbildningsområde
ORDER BY Utbildning DESC;

 utbildning |              utbildningsområde
------------+----------------------------------------------
        289 | Data/IT
        261 | Ekonomi, administration och försäljning
        204 | Teknik och tillverkning
        185 | Samhällsbyggnad och byggteknik
        139 | Hälso- och sjukvård samt socialt arbete
         54 | Kultur, media och design
         38 | Lantbruk, djurvård, trädgård, skog och fiske
         34 | Hotell, restaurang och turism
         20 | Säkerhetstjänster
         18 | Transporttjänster
         10 | Friskvård och kroppsvård
          7 | Journalistik och information
          6 | Pedagogik och undervisning
          5 | Juridik
          2 | Övrigt
(15 rows)

D) Count nubmer of approved programs for each municipality (kommun).

SELECT 
    COUNT(utbildningsnamn) AS Utbildning,
    kommun
FROM myh_2024
GROUP BY kommun
ORDER BY Utbildning DESC;

E) Calculate the percentage of approved programs within each education category.

SELECT
    utbildningsområde,
    COUNT(CASE WHEN Beslut = 'Beviljad' THEN 1 END) AS approved_programs,
    ROUND(
        (COUNT(CASE WHEN Beslut = 'Beviljad' THEN 1 END) * 100.0) / COUNT(*), 
        2
    ) AS approval_percentage
FROM myh_2024
GROUP BY utbildningsområde
ORDER BY approval_percentage DESC;